### ISSUE TITLE
הודעת שגיאה לאחר עדכון אחרון מעכשיו כשמנסה להתחבר

### ISSUE THREAD

**Issue by shaulmani** [adam2314/linet3#414]
Fatal error: Can't use method return value in write context in /var/www/install/protected/models/Docs.php on line 272

**Comment by aribhour** [comment]
Checking wait please

בברכה
ארי בן חור
[mms]
גבעת גאולה 1 רמת גן 52215
נייד:    0524780789
טלפון: 0772105001
פקס:   0775611355
http://www.speedcomp.co.il<http://www.speedcomp.co.il/>

**Comment by shaulmani** [comment]
הבהרה : אני מתחבר, מגיע למסך בחר חברה, בוחר את החברה ואז מתקבלת ההודעה גם לאחר כיבוי והדלקה

**Comment by aribhour** [comment]
The update caused the application to crash.
We blocked the update in order to prevent further damage to other people..
Later on today we are going to fix the issue:
1. We will publish a new update.
2. For the people that have already have their program crashed, we will publish a detailed procedure instructions how to fix the issue.

**Comment by adam2314** [comment]
Hey 
after you login and select a company please direct your browser to http://127.0.0.1:85/newupdate and run the update wizard it will solve all of your problems

**Comment by aribhour** [comment]
Shaul and every affected Linet 3 users,
If you have the application crashed, the proper way to fix it is the following procedure:
1. Browse into the application and login
2. You get an error window. Don't panic :-)
3. Change the address in the address bar to http://127.0.0.1:85/newupdate 
4. Run the update wizard.
5. Wait until it compketes
6. All should be alright now :-)
