### ISSUE TITLE
Print document

### ISSUE THREAD

**Issue by dan-omniscience** [adam2314/linet3#455]
Hi Adam,

The print document button currently send the html page of the invoice to print without creating a signed pdf file(without the "computerized document" statement, in my opinion when clicking the print button the system should create a sign pdf then send it to the print.

**Comment by aribhour** [comment]
You are absolutely wrong. This is the way the application should react to a user request to print: directly print from html. This is due to Israel tax authority regulations.
Creating any kind of file that can be reprinted multiple times without digitally  signing it and without marking it as a "computerised document" is strictly and explicitly forbidden.

**Comment by dan-omniscience** [comment]
Ok, I understand. thank you for explaining this.
I still think that a sign pdf file should be created in the system as well but maybe I'm wrong about it as well, can you elaborate about it please? 

Maybe we can add the option to change the default button action in the settings, for example my use and many other in the digital field would probably prefer that the default action would be a sign pdf and not a print, What do you think?

**Comment by aribhour** [comment]
There is a separate option to produce a signed pdf file. Check out the little black arrow on the print button....

**Comment by dan-omniscience** [comment]
I know there is that option, I suggested the possibility to change the
default option. Please note the other issue I created that was caused by my
misuse, of the print option. I'm simply want to try and simplify the use of
the system for my needs and for others that might have the same workflow.

**Comment by aribhour** [comment]
Dan,
Thanks for clarifying your wishes, but the default option to print straight out from html is not going to change because the vast majority of accountants and self owned business owners are used to print instead of producing signed computerized documents. Obviously it is going to change the next decade but this is the current users habits at the present....
You are mostly welcome to change the default behavior by yourself.
After all, this is the purpose and the main reason d'etre of the open source programming idea.
