### ISSUE TITLE
Migrating to Linet from other accounting software

### ISSUE THREAD

**Issue by 86ds8DR** [adam2314/linet3#546]
Is it possible? Currently I use Frontaccounting. What are my options to start using Linet? I'm not an accountant, just a small entrepreneur.

**Comment by starnetwork** [comment]
I belive it's possible, you just need some "custom work" with paid working time

**Comment by aribhour** [comment]
If you are willing to go on with importing data from Frontaccounting with paid support please contact us at 972722711800 or within Israel 0722711800

**Comment by 86ds8DR** [comment]
I cannot afford to pay. Is there any way I can do it by myself?
Related question: may be, instead of migrating the database and all from FromAccounting I may just start Linet, say, from 1.1.2016 (a new fiscal year) using just a few values from some summary of the previous year? More generally, if one starts to use a new accounting software, does he must to import all the transactions from the previous years?

**Comment by aribhour** [comment]
Even if you are a programer it will be very difficult.
Technicaly you can start using Linet in a new fiscal year from fresh without all the data imported from previous programs\years. As for "summary"  data of previous years: Linet is capable to register balances of accounts from previous years/accounting apps. This way your accounts will be well balanced. As to the question if this kund of transition is allowed I suppose you imply to being ok with local regulation in your country of residence? I suppose that the regulations are flexible enough not to bind you forcefully to an accounting app to a lifetime but this is a question you have to ask local proffesional cpa in your country to be on the safe side...

**Comment by 86ds8DR** [comment]
I am an Israeli, small business ("esek patur"), any hints regarding regulations here relating this issue?
I know that double-siding accounting is overkill, I just like it.

**Comment by aribhour** [comment]
If you are an Israeli how come you used an accounting app which is not complying Israeli regulation?
Second thought: don't answer that question there are some things better not knowing...
Anyway, as far as I know you absolutly can start fresh even in the middle of fiscal year the only condition is to keep document numbering scheme consistant with the old system.
Starting from fresh a new fiscal year is even easier since you can start document numbering as you wish.
This is what I know and certainly not a proffesional answer. You should consult a CPA before final desetion.
