### ISSUE TITLE
Change invoice issue date

### ISSUE THREAD

**Issue by wottem** [adam2314/linet3#625]
Hi. 
There isn't any posibility of changing the invoice issue date. Is there's a way to allow controlling the issue date?

**Comment by aribhour** [comment]
No, issue date is obligatory locked up by Israeli tax authorities' regulation

**Comment by wottem** [comment]
But in other Israeli platform this option is available (i.e greenvoice/Invoice Maven)

**Comment by aribhour** [comment]
If it is true, this is absolutely amazing that such well known web services ignore regulations as we we understand them. In Hashavshevet and rivhit , as far as I know, this option is not available.
Can you send screenshots?

**Comment by wottem** [comment]
## Greenvoice
![2](https://cloud.githubusercontent.com/assets/10073175/12276159/f0291c0c-b97c-11e5-89b4-7dd99598ceb7.PNG)
![default](https://cloud.githubusercontent.com/assets/10073175/12276161/f02ce670-b97c-11e5-9b7f-26402e686ff2.PNG)
## Invoice Maven
![maven](https://cloud.githubusercontent.com/assets/10073175/12276160/f029826e-b97c-11e5-86ba-23eb1dcff175.PNG)

**Comment by aribhour** [comment]
Now the issue is clearer: In both applications the issue date of a new produced invoice is flexible only to the extent of the issue date of the last invoice produced within the system. 
Linet doesn't support that kind of limited flexibility since it's legality is in question. and unclear.
If you have clear evidence that tax authority is approving this kind of flexibility please notify here and we will be glad to enable the feature in a day or two.

**Comment by aribhour** [comment]
Trying to get a cpa opinion about the issue

**Comment by shaulmani** [comment]
שלום
לינט תוכנה רשומה במס הכנסה בישראל ולכן עליה לעמוד בהוראות החוק הכוללות דרישות מסוימות
בין היתר
תאריך הפקת מסמך חייב להיות יום ההפקה בפועל ללא אפשרות שינוי תאריך זה
יש תוכנות המאפשרות שינוי התאריך בתחום האפור שבין יום הפקת המסמך האחרון ליום ההפקה בפועל
הנושא עדיין לא עמד במבחן משפטי ולכן מתן אפשרות זו, כמו גם שינוי תאריך המחשב לצורך הפקת מסמך בתאריך הרצוי, עלול להיות למכשול בביקורת ניהול ספרים
